-- PIN-based auth for business-org team members created by an owner/admin.
--
-- The PIN is deliberately NEVER the literal Supabase Auth password: a short
-- numeric PIN's keyspace is too small to trust to GoTrue's own rate
-- limiting. Instead, each PIN-managed user also gets a synthetic
-- internal_email + a long random auth_secret (the real GoTrue password,
-- never sent to any client) generated by create-team-member. login-with-pin
-- (Edge Function) is the only path that ever turns a correct PIN into a
-- real session, and it owns its own attempt-counting/lockout against this
-- table via attempt_pin_login below.
--
-- RLS is enabled with ZERO policies for `authenticated` — identical pattern
-- to organization_ai_keys (0021): all access goes through the
-- SECURITY DEFINER functions here/0026, or a service-role Edge Function.

create table public.member_pin_credentials (
  user_id uuid primary key references auth.users (id) on delete cascade,
  organization_id uuid not null references public.organizations (id) on delete cascade,
  phone text not null,
  internal_email text not null unique,
  pin_hash text not null,
  auth_secret text not null,
  failed_attempts integer not null default 0,
  locked_until timestamptz,
  last_login_at timestamptz,
  created_by uuid not null references auth.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index idx_member_pin_credentials_phone on public.member_pin_credentials (phone);
create index idx_member_pin_credentials_org on public.member_pin_credentials (organization_id);

alter table public.member_pin_credentials enable row level security;
-- Intentionally no policies for `authenticated`.

create trigger set_updated_at before update on public.member_pin_credentials
  for each row execute function public.set_updated_at();

-- Hashing primitive, service-role only (used by create-team-member and
-- regenerate_member_pin).
-- search_path includes `extensions`: this Supabase project has pgcrypto
-- installed there (Supabase's default), not in `public` — confirmed via
-- `select extnamespace::regnamespace from pg_extension where
-- extname='pgcrypto'` returning `extensions`.
create or replace function public.hash_pin(p_pin text)
returns text
language sql
security definer
set search_path = public, extensions
as $$
  select crypt(p_pin, gen_salt('bf'));
$$;

grant execute on function public.hash_pin(text) to service_role;

-- Atomic finish-up for account creation: called by create-team-member AFTER
-- auth.admin.createUser() has already made the auth.users row (which fires
-- handle_new_user and creates the profiles row), so every remaining write
-- happens in one transaction — all-or-nothing — rather than as three
-- separate serviceClient calls that could partially fail.
create or replace function public.finalize_team_member(
  p_user_id uuid,
  p_organization_id uuid,
  p_role text,
  p_phone text,
  p_internal_email text,
  p_pin_hash text,
  p_auth_secret text,
  p_created_by uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_role not in ('accountant', 'member') then
    raise exception 'invalid role for a PIN-managed team member: %', p_role;
  end if;

  update public.profiles set phone = p_phone where id = p_user_id;

  insert into public.organization_members (organization_id, user_id, role)
  values (p_organization_id, p_user_id, p_role);

  insert into public.member_pin_credentials (
    user_id, organization_id, phone, internal_email, pin_hash, auth_secret, created_by
  ) values (
    p_user_id, p_organization_id, p_phone, p_internal_email, p_pin_hash, p_auth_secret, p_created_by
  );
end;
$$;

grant execute on function public.finalize_team_member(uuid, uuid, text, text, text, text, text, uuid) to service_role;

-- The whole login decision, atomic: lookup + lockout check + attempt
-- counting + PIN verification happen inside one implicit transaction, so
-- two concurrent wrong guesses can't race past the lockout threshold, and
-- login-with-pin stays a thin wrapper around this one call.
create or replace function public.attempt_pin_login(p_phone text, p_pin text)
returns table (
  outcome text,                 -- 'ok' | 'invalid' | 'locked' | 'disabled'
  out_user_id uuid,
  out_internal_email text,
  out_auth_secret text,
  retry_after_seconds integer
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_row public.member_pin_credentials%rowtype;
begin
  select * into v_row from public.member_pin_credentials where phone = p_phone;

  if v_row.user_id is null then
    -- Dummy bcrypt compare so "no such phone" and "wrong PIN" take roughly
    -- the same time and return the same generic outcome — avoids letting a
    -- caller enumerate which phone numbers are registered.
    perform crypt(p_pin, '$2a$06$abcdefghijklmnopqrstuv');
    return query select 'invalid'::text, null::uuid, null::text, null::text, null::integer;
    return;
  end if;

  if v_row.locked_until = 'infinity'::timestamptz then
    return query select 'disabled'::text, null::uuid, null::text, null::text, null::integer;
    return;
  end if;

  if v_row.locked_until is not null and v_row.locked_until > now() then
    return query select 'locked'::text, null::uuid, null::text, null::text,
      ceil(extract(epoch from (v_row.locked_until - now())))::integer;
    return;
  end if;

  if v_row.pin_hash = crypt(p_pin, v_row.pin_hash) then
    update public.member_pin_credentials
      set failed_attempts = 0, locked_until = null, last_login_at = now(), updated_at = now()
      where user_id = v_row.user_id;
    return query select 'ok'::text, v_row.user_id, v_row.internal_email, v_row.auth_secret, null::integer;
    return;
  end if;

  if v_row.failed_attempts + 1 >= 5 then
    update public.member_pin_credentials
      set failed_attempts = 0, locked_until = now() + interval '15 minutes', updated_at = now()
      where user_id = v_row.user_id;
    return query select 'locked'::text, null::uuid, null::text, null::text, (15 * 60)::integer;
  else
    update public.member_pin_credentials
      set failed_attempts = failed_attempts + 1, updated_at = now()
      where user_id = v_row.user_id;
    return query select 'invalid'::text, null::uuid, null::text, null::text, null::integer;
  end if;
end;
$$;

grant execute on function public.attempt_pin_login(text, text) to service_role;
